#!/usr/bin/env bash
#
# Blueprint — WordPress import for the LayTheme build.
#
# GENERATED by blueprint/build.mjs from manifest.json. Do not edit by hand;
# edit the manifest and re-run `node blueprint/build.mjs`.
#
# Imports 38 photographs into the media library and creates the
# 13 Projects, each with its first frame as the featured image.
#
# Run it from the WordPress root, on the server, with WP-CLI installed:
#
#   POST_TYPE=project ./import-projects.sh /path/to/blueprint/images/full
#
# Check the post type slug first — LayTheme's portfolio post type is commonly
# 'project', but confirm with:  wp post-type list --format=table
#
set -euo pipefail

IMAGES="${1:-./images/full}"
POST_TYPE="${POST_TYPE:-project}"

if ! command -v wp >/dev/null 2>&1; then
  echo "WP-CLI ('wp') not found. Install it, or use the manual route in LAYTHEME-SETUP.md." >&2
  exit 1
fi

if [ ! -d "$IMAGES" ]; then
  echo "Image folder not found: $IMAGES" >&2
  exit 1
fi

if ! wp post-type list --field=name | grep -qx "$POST_TYPE"; then
  echo "Post type '$POST_TYPE' does not exist in this install." >&2
  echo "Run 'wp post-type list --format=table' and re-run with POST_TYPE=<slug>." >&2
  exit 1
fi

# Imports one file and prints its new attachment ID.
import_image() {
  wp media import "$IMAGES/$1" --title="$2" --porcelain
}

# ---- 01 / 13 — Bandits ---------------------------------------
project_1() {
  local ids=() pid
  echo "==> 01 Bandits (8 frames)"
  ids+=("$(import_image "bandits-1.jpg" "Bandits — frame 01")")
  ids+=("$(import_image "bandits-2.jpg" "Bandits — frame 02")")
  ids+=("$(import_image "bandits-3.jpg" "Bandits — frame 03")")
  ids+=("$(import_image "bandits-4.jpg" "Bandits — frame 04")")
  ids+=("$(import_image "bandits-5.jpg" "Bandits — frame 05")")
  ids+=("$(import_image "bandits-6.jpg" "Bandits — frame 06")")
  ids+=("$(import_image "bandits-7.jpg" "Bandits — frame 07")")
  ids+=("$(import_image "bandits-8.jpg" "Bandits — frame 08")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Bandits" \
    --post_name="bandits" \
    --post_excerpt="Salta, Argentina" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 02 / 13 — Charros ---------------------------------------
project_2() {
  local ids=() pid
  echo "==> 02 Charros (8 frames)"
  ids+=("$(import_image "charros-1.jpg" "Charros — frame 01")")
  ids+=("$(import_image "charros-2.jpg" "Charros — frame 02")")
  ids+=("$(import_image "charros-3.jpg" "Charros — frame 03")")
  ids+=("$(import_image "charros-4.jpg" "Charros — frame 04")")
  ids+=("$(import_image "charros-5.jpg" "Charros — frame 05")")
  ids+=("$(import_image "charros-6.jpg" "Charros — frame 06")")
  ids+=("$(import_image "charros-7.jpg" "Charros — frame 07")")
  ids+=("$(import_image "charros-8.jpg" "Charros — frame 08")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Charros" \
    --post_name="charros" \
    --post_excerpt="Jalisco, Mexico" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 03 / 13 — Back Forty ------------------------------------
project_3() {
  local ids=() pid
  echo "==> 03 Back Forty (6 frames)"
  ids+=("$(import_image "back-forty-1.jpg" "Back Forty — frame 01")")
  ids+=("$(import_image "back-forty-2.jpg" "Back Forty — frame 02")")
  ids+=("$(import_image "back-forty-3.jpg" "Back Forty — frame 03")")
  ids+=("$(import_image "back-forty-4.jpg" "Back Forty — frame 04")")
  ids+=("$(import_image "back-forty-5.jpg" "Back Forty — frame 05")")
  ids+=("$(import_image "back-forty-6.jpg" "Back Forty — frame 06")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Back Forty" \
    --post_name="back-forty" \
    --post_excerpt="Private Ranch" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 04 / 13 — Off Grid --------------------------------------
project_4() {
  local ids=() pid
  echo "==> 04 Off Grid (2 frames)"
  ids+=("$(import_image "off-grid-1.jpg" "Off Grid — frame 01")")
  ids+=("$(import_image "off-grid-2.jpg" "Off Grid — frame 02")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Off Grid" \
    --post_name="off-grid" \
    --post_excerpt="Lewis Ferris" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 05 / 13 — Deep End --------------------------------------
project_5() {
  local ids=() pid
  echo "==> 05 Deep End (1 frames)"
  ids+=("$(import_image "deep-end-1.jpg" "Deep End — frame 01")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Deep End" \
    --post_name="deep-end" \
    --post_excerpt="Studio" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 06 / 13 — Dive Bar --------------------------------------
project_6() {
  local ids=() pid
  echo "==> 06 Dive Bar (1 frames)"
  ids+=("$(import_image "dive-bar-1.jpg" "Dive Bar — frame 01")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Dive Bar" \
    --post_name="dive-bar" \
    --post_excerpt="Agustin Farias" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 07 / 13 — Static ----------------------------------------
project_7() {
  local ids=() pid
  echo "==> 07 Static (2 frames)"
  ids+=("$(import_image "static-1.jpg" "Static — frame 01")")
  ids+=("$(import_image "static-2.jpg" "Static — frame 02")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Static" \
    --post_name="static" \
    --post_excerpt="Ivan Resnik" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 08 / 13 — Hang In There ---------------------------------
project_8() {
  local ids=() pid
  echo "==> 08 Hang In There (1 frames)"
  ids+=("$(import_image "hang-in-there-1.jpg" "Hang In There — frame 01")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Hang In There" \
    --post_name="hang-in-there" \
    --post_excerpt="Cecilia Di Paolo" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 09 / 13 — Soft Landing ----------------------------------
project_9() {
  local ids=() pid
  echo "==> 09 Soft Landing (4 frames)"
  ids+=("$(import_image "soft-landing-1.jpg" "Soft Landing — frame 01")")
  ids+=("$(import_image "soft-landing-2.jpg" "Soft Landing — frame 02")")
  ids+=("$(import_image "soft-landing-3.jpg" "Soft Landing — frame 03")")
  ids+=("$(import_image "soft-landing-4.jpg" "Soft Landing — frame 04")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Soft Landing" \
    --post_name="soft-landing" \
    --post_excerpt="Chris Abatzis" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 10 / 13 — Tones -----------------------------------------
project_10() {
  local ids=() pid
  echo "==> 10 Tones (1 frames)"
  ids+=("$(import_image "tones-1.jpg" "Tones — frame 01")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Tones" \
    --post_name="tones" \
    --post_excerpt="Chris Abatzis" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 11 / 13 — Another Planet --------------------------------
project_11() {
  local ids=() pid
  echo "==> 11 Another Planet (1 frames)"
  ids+=("$(import_image "another-planet-1.jpg" "Another Planet — frame 01")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Another Planet" \
    --post_name="another-planet" \
    --post_excerpt="Field Study" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 12 / 13 — Silhouette ------------------------------------
project_12() {
  local ids=() pid
  echo "==> 12 Silhouette (1 frames)"
  ids+=("$(import_image "silhouette-1.jpg" "Silhouette — frame 01")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Silhouette" \
    --post_name="silhouette" \
    --post_excerpt="Grant Spanier" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

# ---- 13 / 13 — Kin -------------------------------------------
project_13() {
  local ids=() pid
  echo "==> 13 Kin (2 frames)"
  ids+=("$(import_image "kin-1.jpg" "Kin — frame 01")")
  ids+=("$(import_image "kin-2.jpg" "Kin — frame 02")")

  pid=$(wp post create \
    --post_type="$POST_TYPE" \
    --post_title="Kin" \
    --post_name="kin" \
    --post_excerpt="Nick Fancher" \
    --post_status=publish \
    --porcelain)

  # First frame becomes the featured image, so the project shows up in the
  # homepage Element Grid before its Gridder layout exists.
  wp post meta update "$pid" _thumbnail_id "${ids[0]}"
  echo "    post $pid, attachments: ${ids[*]}"
}

project_1
project_2
project_3
project_4
project_5
project_6
project_7
project_8
project_9
project_10
project_11
project_12
project_13

echo
echo "Done: 13 projects, 38 attachments."
echo "Next: Lay Options -> Images -> set JPG quality 80-85, then 'wp media regenerate --yes'."
echo "Then build the Gridder layouts — see LAYTHEME-SETUP.md, step 6 onwards."
